// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtjhk-xkr0Zn1mwEhteUG0tWWzhi6OHE',
    appId: '1:602893255620:web:07949de433a05245f79a91',
    messagingSenderId: '602893255620',
    projectId: 'chat-app-43dd6',
    authDomain: 'chat-app-43dd6.firebaseapp.com',
    storageBucket: 'chat-app-43dd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoV0JTDrlLKg1Av-7b816fkRNQuXJN6s',
    appId: '1:602893255620:android:f6ef429b60729fd9f79a91',
    messagingSenderId: '602893255620',
    projectId: 'chat-app-43dd6',
    storageBucket: 'chat-app-43dd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOqoFsybSkY3BAR0UyY-91Xnd_jQ1YOGQ',
    appId: '1:602893255620:ios:b167fe338a14e2fff79a91',
    messagingSenderId: '602893255620',
    projectId: 'chat-app-43dd6',
    storageBucket: 'chat-app-43dd6.appspot.com',
    iosClientId: '602893255620-2ou91q1q0t3erdigng5jlf3svssqvhc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOqoFsybSkY3BAR0UyY-91Xnd_jQ1YOGQ',
    appId: '1:602893255620:ios:b167fe338a14e2fff79a91',
    messagingSenderId: '602893255620',
    projectId: 'chat-app-43dd6',
    storageBucket: 'chat-app-43dd6.appspot.com',
    iosClientId: '602893255620-2ou91q1q0t3erdigng5jlf3svssqvhc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
